# Acknowledgments {.unnumbered #sec-ack}

## Acknowledgments

This book was compiled during CS329H: Machine Learning from Human Preferences at Stanford University in Fall 2023 and Fall 2024. We thank Rehaan Ahmad, Ahmed Ahmed, Jirayu Burapacheep, Michael Byun, Akash Chaurasia, Andrew Conkey, Tanvi Deshpande, Eric Han, Laya Iyer, Adarsh Jeewajee, Shreyas Kar, Arjun Karanam, Jared Moore, Aashiq Muhamed, Bidipta Sarkar, William Shabecoff, Stephan Sharkov, Max Sobol Mark, Kushal Thaman, Joe Vincent, Yibo Zhang, Duc Nguyen (VNU-HCM University of Technology), Grace Sodunke (University of Oxford), and Ky Nguyen (DePauw University) for their help in compiling this book. We appreciate the time of our guest speakers, including Pat Langley (Institute for the Study of Learning and Expertise), Meredith Ringel Morris (Google DeepMind), Vasilis Syrgkanis (Stanford), Jason Hartline (Northwestern), Dorsa Sadigh (Stanford), Diyi Yang (Stanford), and Nathan Lambert (AI2).

::: {.content-visible when-format="html"}

## Citation
Thanks for reading our book! We hope you find this book useful in your research and teaching.

::: {#quarto-appendix .default}
BibTeX citation:
<pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@book{mlhp,
  author    = {Truong, Sang and Haupt, Andreas and Koyejo, Sanmi},
  title     = {{Machine Learning from Human Preferences}},
  year      = {2024},
  publisher = {Stanford University},
  doi       = {},
  note      = {}
}</code></pre>

For attribution, please cite this work as:
<div id="ref-mlhp" class="csl-entry quarto-appendix-citeas">
  S. Truong, A. Haupt, and S. Koyejo. 2024. Machine Learning from Human Preferences. Stanford University.
</div>
:::

:::
